baseURL = "https://vishvAsa.github.io/bhAShAntaram/"
languageCode = "en-us"
title = "भाषान्तरेषु विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/bhAShAntaram/edit/content/"
  contactLink = "https://github.com/vvasuki/bhAShAntaram/issues/new"
  fullSearchURL = "/full_search"
  env = "production"
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true